apiVersion: v1
kind: Service
metadata:
  name: django-poll-app-service
spec:
  type: NodePort
  selector:
    app: django-poll-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000

