apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-poll-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-poll-app
  template:
    metadata:
      labels:
        app: django-poll-app
    spec:
      containers:
      - name: django-poll-app
        image: gym14714/jordan
        ports:
        - containerPort: 8000
